# Generated by Django 6.0 on 2025-12-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='room_number',
            field=models.CharField(default='unspecified', help_text="Room, House, or Unit Number (e.g., 'Room 12')", max_length=50),
        ),
    ]
